spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate.show_sql: true
    hibernate.ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: saipavan.samala@gmail.com
    password: hdboxablscsxlcaa
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
